server:
  port: 8081
spring:
  application:
    name: service-school
  dataSource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/school_db
    username: postgres
    password: dhia
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: 'update'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    prefer-ip-adress: true
    ip-adress: 127.0.0.1
    hostname: localhost