server:
  port: 8082
spring:
  application:
    name: service-student
  data:
    mongodb:
      uri: mongodb://localhost:27017/st
  jpa:
    show-sql: false
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      format_sql: false
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'